name: node
version: '12.22.7'
summary: Node.js
description: |
  A JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. https://nodejs.org/

grade: stable
confinement: classic

apps:
  node:
    command: bin/node
  npm:
    command: bin/npm
  npx:
    command: bin/npx
  yarn:
    command: bin/yarn.js
  yarnpkg:
    command: bin/yarn.js

parts:
  node:
    plugin: make
    source-type: tar
    source: https://nodejs.org/download/release/v12.22.7/node-v12.22.7.tar.gz
    build-packages:
      - g++
      - make
      - python2.7
    prepare: |
      ./configure --prefix=/ --release-urlbase=https://nodejs.org/download/release/ --tag=
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      echo "prefix = /usr/local" >> $SNAPCRAFT_PART_INSTALL/etc/npmrc
  yarn:
    source-type: tar
    source: https://yarnpkg.com/latest.tar.gz
    plugin: dump
    # Yarn has a problem with lifecycle scripts when used inside snap, they don't complete properly, with exit code !=0.
    # Replacing the spinner with proper stdio appears to fix it.
    install: |
      sed -i "s/var stdio = spinner ? undefined : 'inherit';/var stdio = 'inherit';/" $SNAPCRAFT_PART_INSTALL/lib/cli.js
