name: node
version: '14.18.1'
summary: Node.js
description: |
  A JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. https://nodejs.org/

grade: stable
confinement: classic

apps:
  node:
    command: bin/node
  npm:
    command: bin/npm
  npx:
    command: bin/npx
  yarn:
    command: bin/yarn.js
  yarnpkg:
    command: bin/yarn.js

parts:
  gcc-6:
    plugin: nil
    override-pull: 'true'
    override-build: |
      sudo apt --yes install software-properties-common
      sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
      sudo apt update
      sudo apt --yes install gcc-6 g++-6
    override-stage: 'true'
    override-prime: 'true'
  node:
    plugin: make
    source-type: tar
    source: https://nodejs.org/download/release/v14.18.1/node-v14.18.1.tar.gz
    make-parameters:
      - V=
    prepare: |
      export CC="gcc-6"
      export CXX="g++-6"
      export LINK="g++-6"
      ./configure --verbose --prefix=/ --release-urlbase=https://nodejs.org/download/release/ --tag=
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      echo "prefix = /usr/local" >> $SNAPCRAFT_PART_INSTALL/etc/npmrc
  yarn:
    source-type: tar
    source: https://yarnpkg.com/latest.tar.gz
    plugin: dump
    # Yarn has a problem with lifecycle scripts when used inside snap, they don't complete properly, with exit code !=0.
    # Replacing the spinner with proper stdio appears to fix it.
    install: |
      sed -i "s/var stdio = spinner ? undefined : 'inherit';/var stdio = 'inherit';/" $SNAPCRAFT_PART_INSTALL/lib/cli.js
